### ISSUE TITLE
Allowlist and denylist

### ISSUE THREAD

**Issue by Aspie96** [blacklistisnotracist/blacklist-is-not-a-racist-word#1]
> Allowlist and denylist are more descriptive than whitelist and blacklist. Ok, I can agree with that. Let's start using them for new projects.

I am not so sure about it.

First, "allowlist" and "denylist" would indeed be more descriptive if we had to come up with new terms.

But the words "whitelist" and "blacklist" are so common already that they probably convey meaning easier than "allowlist" and "denylist". In addition, "whitelist" and "blacklist", precisely because are already used in older projects, provide more consistency.

In addition, inviting to replace the words for future projects would send the wrong message that using "whitelist" and "blacklist" are indeed "bad" to use, which they aren't.

Although I wouldn't actively suggest to stick with these words, if one prefers "allowlist" and "denylist", I still think it's better not to suggest to switch to different words either.

**Comment by BlNotRacist** [comment]
Good point. I'll reflect your request in my new repo:
https://github.com/BlNotRacist/blacklist-is-not-a-racist-word

**Comment by Aspie96** [comment]
Are you the same as the author of this repo?
If so, why did you create a new repo? This one already has some stars.

**Comment by Aspie96** [comment]
Ok my question was answered in #2.
